apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: okane

resources:
  - ../../base

images:
  - name: docker.io/library/main
    newTag: prod
  - name: docker.io/library/web
    newTag: prod
