apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  namespace: okane
spec:
  replicas: 1
  selector:
    matchLabels: { app: main }
  template:
    metadata:
      labels: { app: main }
    spec:
      containers:
        - name: main
          image: main:prod
          # don't try to pull from remote
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4321
          env:
            # TODO: ustawiÄ‡ envy
            - name: JWT_SECRET
              value: sekretny-sekret
            - name: OPENAI_API_KEY
              value: openai-api-key
            - name: REDIS_URL
              value: redis://redis:6379
