apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  namespace: okane
spec:
  replicas: 1
  selector:
    matchLabels: { app: main }
  template:
    metadata:
      labels: { app: main }
    spec:
      initContainers:
        - name: migrate
          image: docker.io/library/main:prod
          command:
            - sh
            - -c
            - |
              until getent hosts postgres; do
                echo "Waiting for postgres..."
                sleep 1
              done

              until nc -z postgres 5432; do
                sleep 1
              done
              npx drizzle-kit migrate
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/okane
      containers:
        - name: main
          image: docker.io/library/main:prod
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4321
          envFrom:
            - secretRef:
                name: main
          env:
            - name: PORT
              value: "4321"
