apiVersion: v1
kind: Secret
metadata:
  name: main
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/okane
  JWT_SECRET: sekretny-sekret
  OPENAI_API_KEY: sekretny-sekret
  REDIS_URL: redis://redis:6379
