apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: okane
  namespace: okane
spec:
  ingressClassName: nginx
  rules:
    - host: web.okane.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # Route web host traffic to the web Service on port 80
                name: web
                port:
                  number: 80
    - host: api.okane.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # Route API host traffic to the main Service on port 80
                name: main
                port:
                  number: 80
