apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - main/deployment.yaml
  - main/service.yaml
  - web/deployment.yaml
  - web/service.yaml
  - ingress/ingress-nginx-lb.yaml
  - ingress/ingress.yaml
