apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: okane
spec:
  replicas: 1
  selector:
    matchLabels: { app: web }
  template:
    metadata:
      labels: { app: web }
    spec:
      containers:
        - name: web
          image: web:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            # TODO: ustawiÄ‡ envy
            - name: NODE_ENV
              value: development
            - name: NEXT_PUBLIC_API_URL
              value: https://example.com
